# Generated by Django 4.1.7 on 2023-03-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
