# Generated by Django 4.1.7 on 2023-03-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_otpdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPDevice',
        ),
    ]
